version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci

  - package-ecosystem: docker
    directory: /dockerfiles
    schedule:
      interval: weekly
    labels: [dependencies, infrastructure]
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, infrastructure]
  - package-ecosystem: npm
    directory: /tools/language-editor/frontend
    schedule:
      interval: weekly
    labels: [dependencies]
  - package-ecosystem: maven
    directory: /tools/language-editor/backend
    schedule:
      interval: weekly
    labels: [dependencies]
