version: 1
scoreboards:
  lobby:
    title-key: lobby.sb-title
    variants:
      idle:
        lines:
          - key: lobby.sb-separator
          - blank: true
          - key: lobby.sb-profile
          - key: lobby.sb-profile-value
          - key: lobby.sb-balance
          - blank: true
          - key: lobby.sb-action-play
          - blank: true
          - key: lobby.sb-network
          - key: lobby.sb-network-online
          - key: lobby.sb-server-value
          - blank: true
          - key: lobby.sb-separator
      queued:
        lines:
          - key: lobby.sb-separator
          - key: lobby.sb-profile
          - key: lobby.sb-profile-value
          - blank: true
          - key: lobby.sb-balance
          - key: lobby.sb-network-online
          - key: lobby.sb-games
          - key: lobby.sb-queue
          - key: lobby.sb-queue-state
          - blank: true
          - key: lobby.sb-server-label
          - key: lobby.sb-server-value
          - key: lobby.sb-separator
